<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'PHPThumb\\Tests' => array($vendorDir . '/masterexploder/phpthumb/tests'),
    'PHPThumb' => array($vendorDir . '/masterexploder/phpthumb/src'),
);
